--- #YAML:1.0
name:               Test-Leaner
version:            0.02
abstract:           A slimmer Test::More for when you favor performance over completeness.
author:
    - Vincent Pit <perl@profvince.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Exporter:             0
    ExtUtils::MakeMaker:  0
    Test::More:           0
requires:
    Exporter:    0
    perl:        5.006
    Test::More:  0
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Test-Leaner
    homepage:    http://search.cpan.org/dist/Test-Leaner/
    license:     http://dev.perl.org/licenses/
    repository:  http://git.profvince.com/?p=perl%2Fmodules%2FTest-Leaner.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
dynamic_config:     0
